apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: admission-issuer
  namespace: mutator
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admission-tls-secret
  namespace: mutator
spec:
  duration: 8760h
  renewBefore: 8000h
  commonName: carmy-kubernetes-webhook.mutator
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
  dnsNames:
    - carmy-kubernetes-webhook
    - carmy-kubernetes-webhook.mutator
    - carmy-kubernetes-webhook.mutator.svc
  issuerRef:
    kind: Issuer
    name: admission-issuer
  secretName: admission-webhook-certs
