apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: carmy-kubernetes-webhook
  name: carmy-kubernetes-webhook
  namespace: mutator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carmy-kubernetes-webhook
  template:
    metadata:
      labels:
        app: carmy-kubernetes-webhook
    spec:
      containers:
        - image: nautiker/admission-webhook
          imagePullPolicy: Always
          name: carmy-kubernetes-webhook
          ports:
          - containerPort: 8443
            name: https
            protocol: TCP
          volumeMounts:
            - name: webhook-certs
              mountPath: "/etc/webhook/certs"
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-webhook-certs
