apiVersion: v1
kind: Service
metadata:
  labels:
    app: carmy-kubernetes-webhook
  name: carmy-kubernetes-webhook
  namespace: mutator
spec:
  type: 
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: carmy-kubernetes-webhook
