apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.serviceNameFront }}
  name: {{ .Values.serviceNameFront }}
  namespace: {{ .Values.nameSpace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceNameFront }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceNameFront }}
    spec:
      containers:
      - name: {{ .Values.serviceNameFront }}
        image: {{ .Values.image.repository }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.containerPort }}
          name: https
          protocol: TCP
        volumeMounts:
          - name: webhook-certs
            mountPath: "/etc/webhook/certs"
            readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-webhook-certs
