apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceNameFront }}
  namespace: {{ .Values.nameSpace }}
  labels:
    name: {{ .Values.serviceNameFront }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: https
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetport }} 
  selector:
    app: {{ .Values.serviceNameFront }}
